"""StackMachine Python SDK."""

from importlib.metadata import PackageNotFoundError, version

from ._async_client import AsyncStackMachine
from ._client import StackMachine
from ._config import RequestOptions
from ._errors import (
    StackMachineAPIError,
    StackMachineAuthenticationError,
    StackMachineConnectionError,
    StackMachineError,
    StackMachineGraphQLError,
    StackMachineInvalidRequestError,
    StackMachinePermissionError,
    StackMachineRateLimitError,
    StackMachineValidationError,
    is_stackmachine_error,
)
from ._models import (
    AppAlias,
    AppSshServer,
    AppVolume,
    DeployApp,
    DeployAppKindWordPress,
    DeployAppVersion,
    DeploymentProgress,
    ExpectedDNSRecord,
    Log,
    Package,
    PackageDistribution,
    PackageVersion,
    SearchPackageVersion,
    SshAuthorizedKey,
    SshUser,
    UploadProgress,
    Viewer,
)
from ._pagination import AsyncStackMachineList, StackMachineList
from ._types import (
    AppAliasSortBy,
    AppsDomainsCreateInput,
    AppsDomainsListInput,
    AppsSshAuthorizedKeysCreateInput,
    AppsSshAuthorizedKeysDeleteInput,
    AppsSshAuthorizedKeysListInput,
    AppsSshServerUpdateInput,
    AppsSshUsersListInput,
    AppsSshUsersUpdateInput,
    AppsVersionsListInput,
    AppsVersionsLogsListInput,
    AppsVolumesCreateInput,
    AppsVolumesListInput,
    AppsVolumesUpdateInput,
    AsyncStackMachineInitSettings,
    CountComparison,
    CountFilter,
    CreateZipFiles,
    DeployAppAutobuildExtraData,
    DeployAppAutobuildInput,
    DeployAppEnvVarInput,
    DeployAppJobDefinitionInput,
    DeployAppsListInput,
    DeployAppsSortBy,
    DeployAppVersionsSortBy,
    DeployAppWordPressExtraData,
    DeploymentFilesInput,
    DeploymentProgressCallback,
    FileInput,
    Headers,
    LogStream,
    PackageOrderBy,
    PackagesFilter,
    PackagesSearchInput,
    PaginationOptions,
    Readable,
    RequestOptionsInput,
    RequestOptionsLike,
    SearchOrderSort,
    SearchPublishDate,
    SshAuthenticationMethod,
    SshTokenCreateResult,
    SshUserPasswordRevealResult,
    SshUserPasswordRotateResult,
    StackMachineInitSettings,
    UploadProgressCallback,
)
from ._uploads import create_zip

try:
    __version__ = version("stackmachine")
except PackageNotFoundError:
    __version__ = "0.4.0"

__all__ = [
    "AppAlias",
    "AppAliasSortBy",
    "AppSshServer",
    "AppVolume",
    "AppsDomainsCreateInput",
    "AppsDomainsListInput",
    "AppsSshAuthorizedKeysCreateInput",
    "AppsSshAuthorizedKeysDeleteInput",
    "AppsSshAuthorizedKeysListInput",
    "AppsSshServerUpdateInput",
    "AppsSshUsersListInput",
    "AppsSshUsersUpdateInput",
    "AppsVersionsListInput",
    "AppsVersionsLogsListInput",
    "AppsVolumesCreateInput",
    "AppsVolumesListInput",
    "AppsVolumesUpdateInput",
    "AsyncStackMachine",
    "AsyncStackMachineInitSettings",
    "AsyncStackMachineList",
    "CountComparison",
    "CountFilter",
    "CreateZipFiles",
    "DeployApp",
    "DeployAppAutobuildExtraData",
    "DeployAppAutobuildInput",
    "DeployAppEnvVarInput",
    "DeployAppJobDefinitionInput",
    "DeployAppKindWordPress",
    "DeployAppVersion",
    "DeployAppVersionsSortBy",
    "DeployAppWordPressExtraData",
    "DeployAppsListInput",
    "DeployAppsSortBy",
    "DeploymentFilesInput",
    "DeploymentProgress",
    "DeploymentProgressCallback",
    "ExpectedDNSRecord",
    "FileInput",
    "Headers",
    "Log",
    "LogStream",
    "Package",
    "PackageDistribution",
    "PackageOrderBy",
    "PackageVersion",
    "PackagesFilter",
    "PackagesSearchInput",
    "PaginationOptions",
    "Readable",
    "RequestOptions",
    "RequestOptionsInput",
    "RequestOptionsLike",
    "SearchOrderSort",
    "SearchPackageVersion",
    "SearchPublishDate",
    "SshAuthenticationMethod",
    "SshAuthorizedKey",
    "SshTokenCreateResult",
    "SshUser",
    "SshUserPasswordRevealResult",
    "SshUserPasswordRotateResult",
    "StackMachine",
    "StackMachineAPIError",
    "StackMachineAuthenticationError",
    "StackMachineConnectionError",
    "StackMachineError",
    "StackMachineGraphQLError",
    "StackMachineInvalidRequestError",
    "StackMachineList",
    "StackMachineInitSettings",
    "StackMachinePermissionError",
    "StackMachineRateLimitError",
    "StackMachineValidationError",
    "UploadProgress",
    "UploadProgressCallback",
    "Viewer",
    "__version__",
    "create_zip",
    "is_stackmachine_error",
]
